Repository the-mvi/nta-2022, pull requests merged in 2022-12, with the labels that each got.

#75 0382_Lityagin_SM_task2
  0382_Lityagin_SM/ceo.csv
  0382_Lityagin_SM/florentine_business.csv
  0382_Lityagin_SM/task2.ipynb
Labels: invalid, check needed

#86 0382_Azarov_MS_task2
  0382_Azarov_MS/task2.ipynb
Labels: check needed

#102 0382_Pribylov_NA_task2
  0382_Pribylov_NA/ceo.csv
  0382_Pribylov_NA/task2.ipynb
Labels: invalid, check needed

#118 0381_Pecherkin_AS_task2
  0381_Pecherkin_AS/data2/ceo.csv
  0381_Pecherkin_AS/data2/florentine_marital.csv
  0381_Pecherkin_AS/task2.ipynb
Labels: check needed

#120 0382_Kruchkov_AM_task2
  0382_Kruchkov_AM/ceo.csv
  0382_Kruchkov_AM/florentine_marital.csv
  0382_Kruchkov_AM/task2.ipynb
Labels: check needed

#130 0381_Mikhailov_VA_task2
  0381_Mikhailov_VA/ceo.csv
  0381_Mikhailov_VA/task2.ipynb
Labels: invalid, check needed

#127 0382_Gudov_NR_task2
  0382_Gudov_NR/ceo.csv
  0382_Gudov_NR/florentine_marital.csv
  0382_Gudov_NR/task2.ipynb
Labels: check needed

#90 0383_Zhelnin_MY_task2
  0383_Zhelnin_MY/task2.ipynb
  0383_Zhelnin_MY/task2/ceo.csv
  0383_Zhelnin_MY/task2/florentine_marital.csv
Labels: check needed

#122 0383_Rudakova_YV_task2
  0383_Rudakova_YV/task2.ipynb
  0383_Rudakova_YV/task2/ceo.csv
  0383_Rudakova_YV/task2/florentine_marital.csv
Labels: check needed

#146 0383_Rudakova_YV_task3
  0383_Rudakova_YV/task3.ipynb
Labels: check needed

#148 0383_Zhelnin_MY_task3
  0383_Zhelnin_MY/task3.ipynb
Labels: check needed

#121 0382_Shangichev_VA_task2
  0382_Shangichev_VA/task2.ipynb
Labels: check needed

#128 0381_Kiriltsev_DA_task2
  0381_Kiriltsev_DA/datasets/ceo.csv
  0381_Kiriltsev_DA/task2.ipynb
Labels: check needed

#140 0381_Efimov_ND_task3
  0381_Efimov_ND/task3.ipynb
Labels: invalid, check needed

#124 0382_Detkova_AS_task2
  0382_Detkova_AS/data/ceo.csv
  0382_Detkova_AS/data/florentine_business.csv
  0382_Detkova_AS/task2.ipynb
Labels: check needed

#74 0382_Kriventsova_LS_task2
  0382_Kriventsova_LS/ceo.csv
  0382_Kriventsova_LS/florentine_business.csv
  0382_Kriventsova_LS/task2.ipynb
Labels: check needed

#101 0382_Andryushchenko_XS_task2
  0382_Andryushchenko_XS/ceo.csv
  0382_Andryushchenko_XS/florentine_business.csv
  0382_Andryushchenko_XS/task2.ipynb
Labels: check needed

#104 0382_Zlobin_AS_task2
  0382_Zlobin_AS/ceo.csv
  0382_Zlobin_AS/florentine_business.csv
  0382_Zlobin_AS/task2.ipynb
Labels: check needed

#117 0381_Prokhorov_BV_task2
  0381_Prokhorov_BV/ceo.csv
  0381_Prokhorov_BV/task2.ipynb
Labels: invalid, check needed

#145 0383_Petrovskaya_ES_task3
  0383_Petrovskaya_ES/task3.ipynb
Labels: check needed

#157 0383_Alexandrovich_VP_task3
  0383_Alexandrovich_VP/task3.ipynb
Labels: check needed

#83 0381_Balakin_V_task2
  0381_Balakin_V/odd/ceo.csv
  0381_Balakin_V/task2.ipynb
Labels: check needed

#93 0381_Magnitov_SA_task2
  0381_Magnitov_SA/task2.ipynb
  0381_Magnitov_SA/task2/ceo.csv
  0381_Magnitov_SA/task2/florentine_business.csv
Labels: check needed

#105 0381_Ibatov_NE_task2
  0381_Ibatov_NE/task2.ipynb
  0381_Ibatov_NE/task2/ceo.csv
  0381_Ibatov_NE/task2/florentine_business.csv
Labels: check needed

#89 0383_Petrovskaya_ES_task2
  0383_Petrovskaya_ES/task2.ipynb
Labels: invalid

#133 0381_Sarycheva_AA_task2
  0381_Sarycheva_AA/ceo.csv
  0381_Sarycheva_AA/florentine_marital.csv
  0381_Sarycheva_AA/task2.ipynb
Labels: check needed

#199 0383_Penkin_MV_task3
  0383_Penkin_MV/task3.ipynb
Labels: invalid, check needed

#88 0383_Boyarkin_NA_task2
  0383_Boyarkin_NA/ceo.csv
  0383_Boyarkin_NA/florentine_business.csv
  0383_Boyarkin_NA/task1/task1.ipynb
  0383_Boyarkin_NA/task2.ipynb
Labels: invalid, check needed

#87 0382_Zdobnova_KD_task2
  0382_Zdobnova_KD/ceo.csv
  0382_Zdobnova_KD/florentine_marital.csv
  0382_Zdobnova_KD/task2.ipynb
Labels: check needed

#210 0383_Petrovskaya_ES_task1
  0383_Petrovskaya_ES/task1.ipynb
Labels: check needed

#100 0381_Kotov_DA_task2
  0381_Kotov_DA/data1/ceo.csv
  0381_Kotov_DA/task2.ipynb
Labels: check needed

#109 0383_Zenin_PA_task2
  0383_Zenin_PA/task2.ipynb
  0383_Zenin_PA/task2_data/ceo.csv
  0383_Zenin_PA/task2_data/florentine_business (1).csv
Labels: check needed
